enum KEYID {
  BTN_NONE,
  BTN_D1S,
  BTN_D2S,
  BTN_D3S,
  BTN_D4S,
  BTN_UpKey,
  BTN_DownKey,
  BTN_RightKey,
  BTN_LeftKey,
  BTN_OkKey,
  BTN_PWRL,
  BTN_BrightKey,
  BTN_StepKey,
  BTN_4CIN,
  BTN_ModeKey,
  BTN_GridKey,
  BTN_MaskKey,
  BTN_AudioSwKey,
  BTN_VideoSwKey,
  BTN_MenuKey,
  BTN_DPKey,
  BTN_HDMI1Key,
  BTN_HDMI2Key,
  BTN_MuteKey,
  BTN_VolDownKey,
  BTN_VolUpKey,
  BTN_HomeKey,
  BTN_FocusFwKey,
  BTN_FocusBwKey,
  BTN_AudioPJKey,
  BTN_AudioLineKey,
  BTN_AudioBTKey,
  BTN_F3Key,
  BTN_F2Key,
  BTN_F1Key,
  BTN_BTL,
  BTN_BT_TX,
  BTN_BT_RX,
  BTN_HOTKEYL,
  BTN_BATTERY_ON,
  BTN_BATTERY_OFF,
  BTN_BTKEY_SHORT,
  BTN_STEP_1,
  BTN_STEP_4,
  BTN_STEP_8,
  BTN_STEP_16,
  BTN_STEP_64,
  BTN_BLE_POOLING,
  BTN_TOP_LEFT,
  BTN_TOP_RIGHT,
  BTN_BOTTOM_LEFT,
  BTN_BOTTOM_RIGHT,
  BTN_UPLOAD_F1,
  BTN_UPLOAD_F2,
  BTN_UPLOAD_F3,
  BTN_UPLOAD_STOP,
  BTN_CLEAR_BATCH,
  BTN_WARP_TL_X,
  BTN_WARP_TL_Y,
  BTN_WARP_TR_X,
  BTN_WARP_TR_Y,
  BTN_WARP_BL_X,
  BTN_WARP_BL_Y,
  BTN_WARP_BR_X,
  BTN_WARP_BR_Y,
  BTN_GET_WARP,
  BTN_SAVE_WARP,
  BTN_SENSOR_ON,
  BTN_SENSOR_OFF,
  BTN_FOCUS_AUTO,
  BTN_PROTYPE_2,
  BTN_PROTYPE_3,
  BTN_LOADTABLE_103,
  BTN_LOADTABLE_123,
  BTN_LOADTABLE_150,
  BTN_VIDEO_READY,
  BTN_SHOW_OSDMENU,
  BTN_ASK_FORMATBOARD,
  BTN_GET_DEVICEID,
  BTN_SCREEN_PRESETUP,
  BTN_DEWARINNG
}

enum PJMODE {
  ON,
  OFF;
}

enum BTMODE {
  OFF,
  RX,
  TX;
} 
// final Map<String, int> keyid = {
//   'BTN_NONE': 0,
//   'BTN_D1S': 1,
//   'BTN_D2S': 2,
//   'BTN_D3S': 3,
//   'BTN_D4S': 4,
//   'BTN_UpKey': 5,
//   'BTN_DownKey': 6,
//   'BTN_RightKey': 7,
//   'BTN_LeftKey': 8,
//   'BTN_OkKey': 9,
//   'BTN_PWRL': 10,
//   'BTN_BrightKey': 11,
//   'BTN_StepKey': 12,
//   'BTN_4CIN': 13,
//   'BTN_ModeKey': 14,
//   'BTN_GridKey': 15,
//   'BTN_MaskKey': 16,
//   'BTN_AudioSwKey': 17,
//   'BTN_VideoSwKey': 18,
//   'BTN_MenuKey': 19,
//   'BTN_DPKey': 20,
//   'BTN_HDMI1Key': 21,
//   'BTN_HDMI2Key': 22,
//   'BTN_MuteKey': 23,
//   'BTN_VolDownKey': 24,
//   'BTN_VolUpKey': 25,
//   'BTN_HomeKey': 26,
//   'BTN_FocusFwKey': 27,
//   'BTN_FocusBwKey': 28,
//   'BTN_AudioPJKey': 29,
//   'BTN_AudioLineKey': 30,
//   'BTN_AudioBTKey': 31,
//   'BTN_F3Key': 32,
//   'BTN_F2Key': 33,
//   'BTN_F1Key': 34,
//   'BTN_BTL': 35,
//   'BTN_BT_TX': 36,
//   'BTN_BT_RX': 37,
//   'BTN_HOTKEYL': 38,
//   'BTN_BATTERY_ON': 39,
//   'BTN_BATTERY_OFF': 40,
//   'BTN_BTKEY_SHORT': 41,
//   'BTN_STEP_1': 42,
//   'BTN_STEP_4': 43,
//   'BTN_STEP_8': 44,
//   'BTN_STEP_16': 45,
//   'BTN_STEP_64': 46,
//   'BTN_BLE_POOLING': 47,
//   'BTN_TOP_LEFT': 48,
//   'BTN_TOP_RIGHT': 49,
//   'BTN_BOTTOM_LEFT': 50,
//   'BTN_BOTTOM_RIGHT': 51,
//   'BTN_UPLOAD_F1': 52,
//   'BTN_UPLOAD_F2': 53,
//   'BTN_UPLOAD_F3': 54,
//   'BTN_UPLOAD_STOP': 55,
//   'BTN_CLEAR_BATCH': 56,
//   'BTN_WARP_TL_X': 57,
//   'BTN_WARP_TL_Y': 58,
//   'BTN_WARP_TR_X': 59,
//   'BTN_WARP_TR_Y': 60,
//   'BTN_WARP_BL_X': 61,
//   'BTN_WARP_BL_Y': 62,
//   'BTN_WARP_BR_X': 63,
//   'BTN_WARP_BR_Y': 64,
//   'BTN_GET_WARP': 65,
//   'BTN_SAVE_WARP': 66,
//   'BTN_SENSOR_ON': 67,
//   'BTN_SENSOR_OFF': 68,
//   'BTN_FOCUS_AUTO': 69,
//   'BTN_PROTYPE_2': 70,
//   'BTN_PROTYPE_3': 71,
//   'BTN_LOADTABLE_103': 72,
//   'BTN_LOADTABLE_123': 73,
//   'BTN_LOADTABLE_150': 74,
//   'BTN_VIDEO_READY': 75,
//   'BTN_SHOW_OSDMENU': 76,
//   'BTN_ASK_FORMATBOARD': 77,
//   'BTN_GET_DEVICEID': 78,
//   'BTN_SCREEN_PRESETUP': 79,
//   'BTN_DEWARINNG': 80,
// };


